FROM mcr.microsoft.com/dotnet/core/sdk:2.2 AS build-env
WORKDIR /app

COPY ./MyWebShop.Common ./MyWebShop.Common
COPY ./MyWebShop.UserApi ./MyWebShop.UserApi
RUN dotnet restore ./MyWebShop.UserApi/MyWebShop.UserApi.csproj


# COPY . ./
RUN dotnet publish ./MyWebShop.UserApi/MyWebShop.UserApi.csproj -c Release -o out

FROM mcr.microsoft.com/dotnet/core/aspnet:2.2 AS run-env

WORKDIR /app
COPY --from=build-env /app/MyWebShop.UserApi/out .
ENTRYPOINT ["dotnet", "MyWebShop.UserApi.dll"]