version: "3"
services:
  userapi:
     # image: "MyWebShop.UserApi"
     build: 
       context: .
       dockerfile: ./MyWebShop.UserApi/dockerfile
     ports: 
        - "8081:80"
  catalogue:
    build:
      context: .
      dockerfile: ./MyWebShop.Catalogue/dockerfile
    ports: 
        - "8082:80"
