version: "3"
services:
  gateway:
    container_name: gateway.api
    build:
      context: .
      dockerfile: ./MyWebShop.APIGateway/dockerfile
    ports:
     - "8083:80"
    depends_on:
      - userapi
      - catalogue
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  userapi:
     # image: "MyWebShop.UserApi"
    container_name: user.api
    build: 
      context: .
      dockerfile: ./MyWebShop.UserApi/dockerfile
    depends_on:
      - catalogue
  catalogue:
    container_name: catalogue.api
    build:
      context: .
      dockerfile: ./MyWebShop.Catalogue/dockerfile