FROM mcr.microsoft.com/dotnet/core/sdk:2.2 AS build-env
WORKDIR /app

COPY ./MyWebShop.APIGateway/ ./
RUN dotnet restore
RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/core/aspnet:2.2 AS run-env

WORKDIR /app
COPY --from=build-env /app/out .
# ENV ASPNETCORE_URLS=http://+:8083
EXPOSE 80
ENTRYPOINT ["dotnet", "MyWebShop.APIGateway.dll"]